### ISSUE TITLE
Is this zimlet usable in production ?

### ISSUE THREAD

**Issue by ZeikoFr** [Zimbra/zimbra-zimlet-signature-template#3]
HI,

First of all thank you very much for this zimlet, it is currently a pain to manage signature in zimbra but this zimlet seems to solve some issues that I have.

I tried to install the zimlet in a test server in OSE 8.8.15 following this part of the guide : 

https://github.com/Zimbra/zimbra-zimlet-signature-template#installing-the-zimlet

But it seems that it is not enabling the base template present in myconfig.xml and there's no GUI access to modify the template (expected since you mention the base64 that is needed to apply a new template).

I've properly installed the default config file (for testing) : 

`zimbra@zimbra-8815-lab:/tmp$ zmzimletctl configure  /tmp/myconfig.xml
[] INFO: Installing Zimlet config for zimbra-zimlet-signature-template
`

But there's no template available : 
![image](https://user-images.githubusercontent.com/54892453/120294345-63496680-c2c6-11eb-986c-a27eae705b39.png)

Can you help my in understanding where i've messed up ?

Also could you gave me the name of the zimbra theme you're using in the demo screenshot ? I really like it.

Regards

**Comment by barrydegraaff** [comment]
This Zimlet is for Zimbra 9/10 Modern UI. For classic UI check: https://gallery.zetalliance.org/extend/items/view/signature-template
